# Generated by Django 2.2.3 on 2020-04-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worlddata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BigIntegerField(blank=True, null=True)),
                ('deaths', models.BigIntegerField(blank=True, null=True)),
                ('recovered', models.BigIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
