# Generated by Django 2.2.3 on 2020-04-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indiadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BigIntegerField(blank=True, null=True)),
                ('deaths', models.BigIntegerField(blank=True, null=True)),
                ('recovered', models.BigIntegerField(blank=True, null=True)),
                ('week', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
